apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  ports:
    - name: postgresdb-stateful
      port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: postgresdb-stateful
